# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://pritamdalal.github.io',
                'git_url': 'https://github.com/pritamdalal/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.renamed': { 'nbdev_hello_world.renamed.foo': ('renamed.html#foo', 'nbdev_hello_world/renamed.py'),
                                           'nbdev_hello_world.renamed.say_hello': ( 'renamed.html#say_hello',
                                                                                    'nbdev_hello_world/renamed.py')}}}
