"""This is the renamed notebook and module."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_renamed.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../nbs/00_renamed.ipynb 3
def foo(): pass

# %% ../nbs/00_renamed.ipynb 4
def say_hello(to):
    "Say hellow to somebody"
    return f"Hello {to}!"
